### ISSUE TITLE
ERROR RUNNING

### ISSUE THREAD

**Issue by JUICY00000** [DongHuangT1/Geacon#1]
hello, hope u are doing good, 
at first thanks for your repo and for the time u put into it, 
im having error running it, but i think cz i didnt modify [profile.go](https://github.com/DongHuangT1/Geacon/blob/master/core/profile.go) as i should be :
![22](https://user-images.githubusercontent.com/91303729/141642761-20cac5c2-53de-4575-ad61-1aeb5294485e.png)
 the only thing i modified was [C2_URL](https://github.com/DongHuangT1/Geacon/blob/5c38417a2d1502253edfca0b2381b382a381e60b/core/profile.go#L13) thats since i didnt know how to fill the other variables in the profile, so how to do it ?

again thanks for your time, and hope u reply soon ;)

**Comment by DongHuangT1** [comment]
C2_URL is the C2 address in the CobaltStrike listener, which supports http, https, tcp listeners.
PullInfo and PushInfo are the information in http-get and http-post in ***.profile.
ProxyURL is the proxy information in the CobaltStrike listener. Please set it to empty if it is not used.
Public_Key is the public key in .cobaltstrike.beacon_keys(You can use [get_RSA.java](https://github.com/WBGlIl/CS_Decrypt/blob/main/get_RSA.java) to get)
The above content is generated by translation, which may cause inconvenience, please forgive me.
```
http-get {
    set uri "/abcd.js";
    header "Pragma"  "no-cache";
    client {
        metadata {
            mask;
            base64url;
            prepend "uuuyyyttt";
            append  "fffgggddd";
            parameter "u";
            // uri-append;
            // header "Cookie";
        }
    }
    server {
        output {
            mask;
            base64;
            append "xxx";
            prepend "qweasd";
            print;
        }
    }
}
-----------------------------------------------
PullInfo = map[string]interface{}{
		"URL":    C2_URL + "/abcd.js",
		"Header": "UHJhZ21hOiBuby1jYWNoZQ==",
		"Output": map[string]string{
			"Coding":  "mask-base64",
			"Append":  "xxx",
			"Prepend": "qweasd",
		},
		"MetaData": map[string]string{
			"Store":   "URL:u",
                        // "Store":   "URL",
                        // "Store":   "Header:Cookie",
			"Coding":  "mask-base64url",
			"Append":  "fffgggddd",
			"Prepend": "uuuyyyttt",
		},
	}
```
