### ISSUE TITLE
使用过程中发现一个问题

### ISSUE THREAD

**Issue by N0puple** [DongHuangT1/Geacon#4]
大佬的代码写的非常棒。但在使用 geacon 的时候发现一个问题，在上线的这个 shell 里，我如果运行一个程序，那么就一定会等这个程序运行完成才会回连。比如我运行一个代理，那么在使用代理的过程中就无法再执行其他的命令。我尝试去解决他，发现是这个 pipe 的问题。尝试将读取 pipe 内容那一段加一个 goroutine，这样会解决这个问题，但是会导致命令执行返回的值不全，挺苦恼的，希望大佬能帮忙解决一下这个问题，感谢！

**Comment by DongHuangT1** [comment]
我试了一下确实存在这个Bug, 本来是为了解决僵尸进程用了Wait, 因此造成这个情况.

**Comment by DongHuangT1** [comment]
我尽快解决这个Bug
