### ISSUE TITLE
建议增加功能

### ISSUE THREAD

**Issue by geekjy** [DongHuangT1/Geacon#7]
socks                     启动SOCKS4代理

  socks stop                 停止SOCKS4
希望能增加socks代理功能

**Comment by DongHuangT1** [comment]
不建议使用CS的SOCKS4, 而且据我所知也很少有人用, 所以不打算添加.

**Comment by geekjy** [comment]
还是有点用，有些环境upload传不上，开个cs的socks4临时用一下

**Comment by DongHuangT1** [comment]
考虑到HTTP流量太频繁，强烈不建议使用CS SOCKS4，请考虑其他方式.
